### PR TITLE
UFOs added

### PR DESCRIPTION
**Pull request by kwichmann**
The also shoot at you! I have not implemented any collisions between UFOs and asteroids, though. Collision between UFOs and player/lasers is a little heavy-handed because it's an image, but it seems to work OK in practice.

Also, I've made the asteroids a little faster with each passing level. The UFOs also get faster, more trigger-happy, and slightly more frequent.

Edit: I used this for collision detection between seekers and ship: http://stackoverflow.com/questions/2049582/how-to-determine-if-a-point-is-in-a-2d-triangle

### CODE REVIEW

**Comment by kwichmann** [comment]
I'm starting to think that this is such a department from the original game, that maybe it should have its own branch? What do you think, @shiffman ?

**Comment by kwichmann** [comment]
I don't know why there was a merge conflict, but it was minor and has been resolved now.

**Comment by shiffman** [comment]
Haha, I just saw the little icon of me in the UFO!   I like the idea of adding the UFOs and think it's a nice feature for this basic version.  I think that maybe we should not add external assets and keep the game as simple drawn elements?   I'd rather have visual variations live in separate forks and linked from here?   This is for two reasons: (1) it's probably going to be too hard to decide what external assets to accept / reject going forward and (b) a simple visual style will work best for the Siraj collaboration?

Let me know what you think.

**Comment by NetStorm84** [comment]
I have drawn the ufo using lines. As I was also working on adding the ufo.
If you merge this I can replace the asset with a line drawn ufo.

**Comment by kwichmann** [comment]
Sounds like it's a good idea to make a separate branch of this. If @NetStorm84 changes it into line graphics we can always merge.

**Comment by NetStorm84** [comment]
Yes, a new branch is a good idea.

**Comment by meiamsome** [comment]
I think a simplistic line UFO would probably be good for this repo...

Perhaps it'd probably be best if @NetStorm84 can PR their UFO line implementation and then we can pick out things from this PR to use?

Open to other options, though.

**Comment by shiffman** [comment]
Hey @NetStorm84 let us know if you still want to work on this, otherwise I'm happy to jump in and help!

**Comment by NetStorm84** [comment]
Go for it Daniel. I haven't really got the time at the moment. Will jump
back in and help with some more after the holidays.

On 29 Dec 2016 13:00, "Daniel Shiffman" <notifications@github.com> wrote:

Hey @NetStorm84 <https://github.com/NetStorm84> let us know if you still
want to work on this, otherwise I'm happy to jump in and help!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/CodingRainbow/Asteroids/pull/46#issuecomment-269627152>,
or mute the thread

**Pull request closed without merging**
