### PR TITLE
Asteroid size

### PR DESCRIPTION
**Pull request by LeastCreative**
implemented asteroid size to have 3 sizes. this will be used in the future to score correctly (100 for small asteroids, 50 for medium, 20 for large)

### CODE REVIEW

**Comment by meiamsome** [comment]
I would have perhaps rebased 1a72755 rather than merging master back into your branch for such a simple case, but other than that this looks good

**Comment by LeastCreative** [comment]
sorry I am still new to go github i am a TFS guy :D

**Comment by meiamsome** [comment]
Is it possible for you to add a commit to your gh-pages branch for me? I pushed the wrong thing and github won't let me reopen without a change. It doesn't have to be anything, I am just going to overwrite it with the correct history

**Comment by LeastCreative** [comment]
sure no problem. do you have google hangouts? Maybe you could give some pointers on git hub and help me figure this all out. my google is evenlesscreative@gmail.com

edit: or other chat would work as well

**Pull request merged**
