### PR TITLE
Ship now spins around center of gravity

### PR DESCRIPTION
**Pull request by kwichmann**
As per issue #26

### CODE REVIEW

**Comment by MunWolf** [comment]
Be careful of this, you also need to change the collision detection to compensate for the changed rendering.

**Review by meiamsome — CHANGES_REQUESTED** [review]
`this.hits` needs to be updated to reflect the change.

**Comment by kwichmann** [comment]
This should fix it.

**Comment by shiffman** [comment]
Nice work @kwichmann!  @meiamsome since you added the original review, do you want to check it out and merge?

**Review by meiamsome — APPROVED** [review]

**Pull request merged**
