### PR TITLE
Update for fun

### PR DESCRIPTION
**Pull request by LeastCreative**
updated movement, added rotation to asteroids, added hud for score and lives, added mild animations.

I am a huge fan! Your videos are exciting unlike literally every other programmer/youtuber in the world. 

I have been working on this all night for no reason, so hopefully someone can enjoy it lol

-Dan Clark

### CODE REVIEW

**Review by meiamsome — COMMENTED** [review]
Hey, just a heads up, it's generally not a good idea to change the level of indentation when making a pull request as it causes the changes algorithm to flag the whole file as changed which makes it hard to see what's been done to what. Your additions look like they're pretty good, though I have yet to try them

**Comment by LeastCreative** [comment]
Oh wow I didn't even think of that. I habitually mash auto format and my ide ignores white space on diffs. I will try to fix it to make it more reasonable later.

**Comment by shiffman** [comment]
This is great!  Also, there are a bunch of conflicts now probably with the indentation changes and also I merged #2 which already implementing the rotation for asteroids.  Can you see if you can redo?  You could also do smaller pull requests for individual features?

**Comment by LeastCreative** [comment]
Sure I will do that when I get home from work. I was up all night and too tired to realize how silly the changes looked.

**Pull request closed without merging**
